<a href="https://colab.research.google.com/github/berfino/Python/blob/main/NumPy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Nedir?

açık kaynak kodlu ücretsiz ve özgür bir kütüphanedir. Numerical Python Sayılarla işlemler yapılır. kütüphanenin en temel elemanı array. 

array ler python listelerinin çok boyutlu olanıdır. array ler listelerden 50 kat daha hızlı çalışır. 
array lerin hızlı çalışmasının sebebi kütüphanenin büyük oranda c ve c++ ile yazılmış olmasıdır. 


In [ ]:
import numpy as np 

In [ ]:
np.array([1,2,3])

#np.arange
#np.linspace
#np.logspace
#np.random


In [ ]:
arr0d = np.array(53)
arr0d

array(53)

In [ ]:
arr1d = np.array([1,2,3,4])
arr1d

array([1, 2, 3, 4])

In [ ]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d = np.array([[[1,2,3]],[[4,5,6],[7,8,9]]])
arr3d

<ipython-input-14-a1780b879bfc>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3d = np.array([[[1,2,3]],[[4,5,6],[7,8,9]]])


array([list([[1, 2, 3]]), list([[4, 5, 6], [7, 8, 9]])], dtype=object)

In [ ]:
arr3d[0]

[[1, 2, 3]]

#Built-in function 

In [ ]:
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(30,50,6, dtype = int)

array([30, 34, 38, 42, 46, 50])

In [ ]:
np.logspace(1,3,5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [ ]:
np.arange(10,105,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [ ]:
np.linspace(0,1000,26, dtype=int)

array([   0,   40,   80,  120,  160,  200,  240,  280,  320,  360,  400,
        440,  480,  520,  560,  600,  640,  680,  720,  760,  800,  840,
        880,  920,  960, 1000])

In [ ]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones((10,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.random.rand(3)

array([0.30207237, 0.17471413, 0.63989706])

In [ ]:
np.random.rand(2,5)

array([[6.56440586e-01, 6.96504163e-01, 7.12004328e-01, 6.30552534e-01,
        7.85213596e-01],
       [5.46343394e-01, 9.43919274e-01, 6.70952604e-04, 5.92684752e-01,
        7.72712800e-02]])

In [ ]:
np.random.rand(2,5) *10

array([[4.89056377, 2.52531274, 5.01244305, 9.4763965 , 7.5335328 ],
       [3.39319826, 8.96404822, 2.60024998, 5.73464659, 2.14491631]])

In [ ]:
np.random.randint(15,50,5)

array([42, 22, 36, 21, 26])

In [ ]:
np.random.randint(15,50,(3,6))


array([[40, 28, 31, 46, 25, 28],
       [31, 29, 30, 24, 15, 44],
       [37, 15, 19, 21, 44, 23]])

In [ ]:
np.random.randint(0,50,(4,6))

array([[44, 28,  8, 32, 43, 45],
       [40, 21, 36,  9,  1, 39],
       [ 4, 20,  4, 40, 14, 13],
       [19, 44, 16, 46, 34, 21]])

#Boyut sayısını ve shape ini kontrol etmek 

In [ ]:
arr0d.ndim

0

In [ ]:
arr2d.shape

(2, 3)

#numpy arraylerini indexleme ve öğelere erişme

In [ ]:
arr2d

array([[22, 23, 34],
       [56, 77, 98]])

In [ ]:
arr2d[0][1]

23

In [ ]:
arr2d[1][0][-1]

IndexError: ignored

In [ ]:
a = np.arange(53,62, dtype=int)
a

array([53, 54, 55, 56, 57, 58, 59, 60, 61])

In [ ]:
a[4]

57

In [ ]:
np.arange(53,62, dtype=int)[4]


57

#numpy dizilerinin max min elemanlarına ve bu elemanların indexlerine erişme 

In [ ]:
arr= np.random.randint(1,100,10)
arr

array([55, 55, 38, 96, 31, 13, 34, 47, 55, 20])

In [ ]:
arr.max()

96

In [ ]:
arr.argmax()


3

In [ ]:
arr.min()

13

In [ ]:
arr.argmin()


5

#numpy arraylerinde slicing 


In [ ]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr[5:11]

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
arr[5:11] = 999
arr

array([  1,   2,   3,   4,   5, 999, 999, 999, 999, 999, 999,  12])

In [ ]:
a = np.arange(-30,10)
a

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9])

In [ ]:
a[5:19]

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

#bir arrayin data type ını kontrol etme 

In [ ]:
a.dtype

dtype('int64')

#bir array in dtype ını değiştirme 

In [ ]:
arr = np.array([1.2,3.4,5.6])
arr

array([1.2, 3.4, 5.6])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr.astype(int)

array([1, 3, 5])

In [ ]:
arr = np.array(['5', '7', '19', '1', '22', '99', '4'])
arr

array(['5', '7', '19', '1', '22', '99', '4'], dtype='<U2')

In [ ]:
arr = arr.astype(int)
arr

array([ 5,  7, 19,  1, 22, 99,  4])

In [ ]:
arr.dtype

dtype('int64')