<a href="https://colab.research.google.com/github/berfino/Python/blob/main/NumPy02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

In [ ]:
np.array([[1,2,3,4],[5,6,7,8],[10,20,30,40]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40]])

In [ ]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.linspace(10,100,6, dtype= int)

array([ 10,  28,  46,  64,  82, 100])

In [ ]:
np.logspace(1,3,20)

array([  10.        ,   12.74274986,   16.23776739,   20.69138081,
         26.36650899,   33.59818286,   42.81332399,   54.55594781,
         69.51927962,   88.58667904,  112.88378917,  143.84498883,
        183.29807108,  233.57214691,  297.63514416,  379.26901907,
        483.29302386,  615.84821107,  784.75997035, 1000.        ])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(3, dtype= int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand()

0.5585306736672369

In [ ]:
np.random.randint(10,20,4)

array([15, 14, 19, 16])

In [ ]:
arr2d = np.array([[1,2,3],[3,4,5]])
arr2d

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d[0][-1]

3

In [ ]:
arr2d.argmax()

5

In [ ]:
arr2d.argmin()

0

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[2:6] =500

In [ ]:
arr

array([  0,   1, 500, 500, 500, 500,   6,   7,   8,   9])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.astype(float)

array([  0.,   1., 500., 500., 500., 500.,   6.,   7.,   8.,   9.])

In [ ]:
arr3d = np.array([[[1,2,3],[4,5,6],[6,7,8]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

##Bir arrayı reshape etme

In [ ]:
# .reshape( metodu arrayin şeklini değiştirmeye yarar)
# .reshape yaparken toplam eleman sayısını sabit tutmaya dikkat etmeli 

In [ ]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

In [ ]:
arr3d.shape

(1, 3, 3)

In [ ]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2d = arr.reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr3d = np.arange(30).reshape(2,3,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
# .reshape kullanılırken hesaplamak istemediğiniz boyut yerine -1 yazarak otomatik hesaplatabilirsiniz.

In [ ]:
arr3d = np.arange(120).reshape(5,2,-1)
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

In [ ]:
arr = np.arange(60,dtype=int)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr3d = arr.reshape(3,2,-1)
arr3d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.shape

(3, 2, 10)

##arrayleri düzleştirme flatten

In [ ]:
# düzleştirme işlemi çok boyutlu bir array i bir boyutlu hale döndürmeye denir 
#basitçe .reshape(-1) metoduyla yapılır 

In [ ]:
arr2d = np.arange(40).reshape(8,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [ ]:
arr2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [ ]:
arr3d = np.arange(60).reshape(-1,5,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [ ]:
arrd = np.arange(30).reshape(3,2,5)
arrd

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
arr = arrd.reshape(-1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(30,)

#Çok boyutlu arraylerde iteration yineleme 

In [ ]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in arr1d: 
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
arr2d =np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for i in arr2d:
  print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for i in arr2d: 
  for x in i:
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
arr3d = np.arange(30).reshape(-1,3,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
for i in arr3d:
  for x in i:
    for y in x:
      print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


#çok boyutlu arraylerde nditer( kullanımı

In [ ]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
for i in np.nditer(arr3d):
  print(i) 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [ ]:
arr = np.arange(120).reshape(2,-1,5)
arr

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119]]])

In [ ]:
for i in np.nditer(arr):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119


#array elemanları arasında 4 işlem

In [ ]:
arr1 = np.array([10,20,50,100])
arr2 = np.array([5,7,9,-1])

In [ ]:
arr1

array([ 10,  20,  50, 100])

In [ ]:
arr2

array([ 5,  7,  9, -1])

In [ ]:
arr1 + arr2

array([15, 27, 59, 99])

In [ ]:
arr1.__add__(arr2)

array([15, 27, 59, 99])

In [ ]:
arr1 - arr2

array([  5,  13,  41, 101])

In [ ]:
arr1.__sub__(arr2)

array([  5,  13,  41, 101])

In [ ]:
arr1 * arr2

array([  50,  140,  450, -100])

In [ ]:
arr1.__mul__(arr2)

array([  50,  140,  450, -100])

In [ ]:
arr1/arr2

array([   2.        ,    2.85714286,    5.55555556, -100.        ])

In [ ]:
arr1//arr2

array([   2,    2,    5, -100])

#bir arrayin toplamına,ort, varyansına, ss bakma

In [ ]:
arr = np.random.randint(0,10,10)
arr

array([3, 3, 8, 1, 6, 4, 3, 8, 1, 4])

In [ ]:
arr.sum()

41

In [ ]:
arr.mean()

4.1

In [ ]:
arr.var()

5.6899999999999995

In [ ]:
arr.std()

2.3853720883753127

In [ ]:
np.sqrt(arr)

array([1.73205081, 1.73205081, 2.82842712, 1.        , 2.44948974,
       2.        , 1.73205081, 2.82842712, 1.        , 2.        ])

In [ ]:
np.sin(arr)

array([ 0.14112001,  0.14112001,  0.98935825,  0.84147098, -0.2794155 ,
       -0.7568025 ,  0.14112001,  0.98935825,  0.84147098, -0.7568025 ])

In [ ]:
arr1 = np.random.randint(0,101,10)
arr1

array([42, 11, 43, 31, 89,  4, 78, 87, 95, 49])

In [ ]:
arr1.sum()

529

In [ ]:
arr1.mean()

52.9

In [ ]:
arr1.var()

972.6899999999999

In [ ]:
arr1.std()

31.187978453243808

#numpy arraylerini birleştirme(concatenate)

In [ ]:
#.concatenate() fonk ile yapılır. fonk içine liste halinde birleştirilecek arrayler vedrilir
#np.concatenate ([arr1,arr2],axis = 1)

In [ ]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([100,200,300,400])

In [ ]:
arr1

array([10, 20, 30, 40])

In [ ]:
arr2

array([100, 200, 300, 400])

In [ ]:
np.concatenate([arr1,arr2], axis=0)

array([ 10,  20,  30,  40, 100, 200, 300, 400])

In [ ]:
arr1 = np.array([[1,2,3],[5,6,7]])
arr2 = np.array([[100,200,300],[56,87,98]])

In [ ]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
arr2

array([[100, 200, 300],
       [ 56,  87,  98]])

In [ ]:
np.concatenate([arr1,arr2],axis=0)

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [ 56,  87,  98]])

In [ ]:
np.concatenate([arr1,arr2],axis=1)


array([[  1,   2,   3, 100, 200, 300],
       [  5,   6,   7,  56,  87,  98]])

#arrayleri stackleme yığınlama işlemleri

In [ ]:
#concatenate işleminin aynısıdır tek farkı yeni bir boyut üzerinde yığınlama yapmasıdır


In [ ]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
arr2

array([[100, 200, 300],
       [ 56,  87,  98]])

In [ ]:
np.concatenate([arr1,arr2],axis=0)

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [ 56,  87,  98]])

In [ ]:
np.stack([arr1,arr2],axis=0)

array([[[  1,   2,   3],
        [  5,   6,   7]],

       [[100, 200, 300],
        [ 56,  87,  98]]])

In [ ]:
#np.hstack() --> satır boyunca yığınlama
#np.vstack() --> sütun boyunca yığınlama

#numpy arraylerinde arama

In [ ]:
#aradığımız değerlerin bulunduğu indexleri döndürmek için np.where( fonksiyonunu kullanırız. 
#np.where( içerisine argüman olarak condition alır)

In [ ]:
arr = np.random.randint(1,10,10)
arr

array([1, 5, 6, 3, 8, 3, 7, 1, 4, 3])

In [ ]:
np.where(arr == 3)# arrayimizin açıncı index olduğunu gösteriyor.

(array([3, 5, 9]),)

In [ ]:
np.where(arr%2 != 0)

(array([0, 1, 3, 5, 6, 7, 9]),)

##numpy random kütüphanesi

In [ ]:
#random diye ayrı bir kütüphane olmasının yanı sıra numoy kütüphanesinin içinde random adında bir moül bulunur.
#numpyin içindeki random modülü normal random kütüphanesinden daha kapsamlıdır. 

In [ ]:
#from numpy import random as rd

In [ ]:
import numpy as np 

In [ ]:
np.random.rand()

0.4878828425730971

In [ ]:
np.random.randn(5)#normal dağılımdan random 5 tane veri çek 

array([-0.30867522, -0.26211233,  0.80214507, -2.30493257,  0.58300824])

In [ ]:
np.random.randint(10,30,5)

array([24, 27, 15, 16, 20])

In [ ]:
np.random.choice(arr)

6